### ISSUE TITLE
[Feature Suggestion] Load apps in Landscape mode

### ISSUE THREAD

**Issue by player301** [hugeBlack/LiveContainer#11]
Make a setting that loads apps in Landscape because in some apps, if livecontainer itself isn’t in landscape mode when running an app that’s normally in landscape mode, it breaks the entire app

**Comment by michael1900** [comment]
> Make a setting that loads apps in Landscape because in some apps, if livecontainer itself isn’t in landscape mode when running an app that’s normally in landscape mode, it breaks the entire app

Yes, it's a necessary option for example with app like kodi. I think there are also other app with same problem.
Hope we can have a fix but i have some doubt in this case. Because if you think at the problem kodi literally loads already in landscape but how to make kodi believe that LC is in landscape when in reality it is not? I am starting to think that is a bit impossible to do.

**Comment by hugeBlack** [comment]
Please try the latest build. I found a janky yet working solution. iPhones only though, rotation lock is not possible on iPad without specifying UIRequiresFullScreen.

**Comment by michael1900** [comment]
> Please try the latest build. I found a janky yet working solution. iPhones only though, rotation lock is not possible on iPad without specifying UIRequiresFullScreen.

Fixed! Thank you!
